title: 'Tests'
methods:
  -
    title: 'Index'
    path: '/tests'
    method: 'get'
    parameters:
      -
        name: 'all'
        type: 'boolean'
      -
        name: 'page'
        type: 'integer'
      -
        name: 'per_page'
        type: 'integer'
    example_responses:
      -
        code: 200
        response: >
          {
            "tests": [
              {
                "id": "5ae30ba01e911e5f128e16d4",
                "title": "Test A",
                "created_at": "27 Apr 2018 at 11:38",
                "questions": [
                  {
                    "id": "5aeadd4e1e911e15a0f200d5",
                    "question": "Q3",
                    "type": "numeric",
                    "order": 1000,
                    "options": [
                      {
                        "id": "5aeadd4e1e911e15a0f200d6",
                        "text": "O11"
                      },
                      {
                        "id": "5aeadd4e1e911e15a0f200d7",
                        "text": "O12"
                      },
                      {
                        "id": "5aeadd4e1e911e15a0f200d8",
                        "text": "O13"
                      }
                    ]
                  }
                ]
              },
              {
                "id": "5ae0667a1e911e1d2f76cc05",
                "title": "Test B",
                "created_at": "25 Apr 2018 at 11:28",
                "questions": []
              }
            ],
            "count": 2
          }

  -
    title: 'Create'
    path: '/tests'
    method: 'post'
    parameters:
      -
        name: 'title'
        type: 'string'
        required: true
        description: 'Name of Test'
      -
        name: 'status'
        type: 'boolean'
        description: 'Is test ready for use'
      -
        name: 'question_ids'
        type: 'array'
        parameters:
          -
            type: 'string'
    example_responses:
      -
        code: 200
        response: >
         {
           "message": "Test has been successfully saved"
         }
        type: 'json'

  -
    title: 'Show'
    path: '/tests/:id'
    method: 'get'
    example_responses:
      -
        code: 200
        response: >
          {
            "test": {
              "id": "5ae30ba01e911e5f128e16d4",
              "title": "Test A",
              "created_at": "27 Apr 2018 at 11:38",
              "questions": [
                {
                  "id": "5aeadd4e1e911e15a0f200d5",
                  "question": "Q3",
                  "type": "numeric",
                  "order": 1000,
                  "options": [
                    {
                      "id": "5aeadd4e1e911e15a0f200d6",
                      "text": "O11"
                    },
                    {
                      "id": "5aeadd4e1e911e15a0f200d7",
                      "text": "O12"
                    },
                    {
                      "id": "5aeadd4e1e911e15a0f200d8",
                      "text": "O13"
                    }
                  ]
                }
              ]
            }
          }
  -
    title: 'Update'
    path: '/tests/:id'
    method: 'put'
    parameters:
      -
        name: 'title'
        type: 'string'
        required: true
        description: 'Name of Test'
      -
        name: 'status'
        type: 'boolean'
        description: 'Is test ready for use'
    example_responses:
      -
        code: 200
        response: >
          {
           "message": "Test has been successfully updated"
          }

  -
    title: 'Delete'
    path: '/tests/:id'
    method: 'delete'
    example_responses:
      -
        code: 200
        type: 'json'